dist: xenial
sudo: false
language: python
cache: pip
matrix:
  include:
    - env: TOXENV=isort-check
    - env: TOXENV=lint
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: linux
      python: 3.4
      env: TOXENV=py34
    - os: linux
      python: 3.5
      env: TOXENV=py35
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: pypy2.7-6.0
      env: TOXENV=pypy
    - os: linux
      python: pypy3.5-6.0
      env: TOXENV=pypy3
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py34
    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py37
install:
  - pip install tox
script:
  - tox
