dist: xenial
sudo: false
language: python
cache: pip
matrix:
  include:
    - python: 3.7
      env: TOXENV=isort-check
    - python: 3.7
      env: TOXENV=lint
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: pypy3.5-6.0
      env: TOXENV=pypy3
install:
  - pip install tox
script:
  - tox
