init:
  - "SET PATH=C:\\Python27\\Scripts;%PATH%"
  - "SET PYTEST_ADDOPTS=-vv"
  - "ECHO PATH=%PATH%"
  - python --version

build: off

environment:
  matrix:
    - TOXENV: "isort-check"
    - TOXENV: "py34-coverage"
    - TOXENV: "py35-coverage"
    - TOXENV: "py36-coverage"
    - TOXENV: "py37-coverage"

install:
  - pip install tox

test_script:
  - tox
