init:
  - "SET PATH=C:\\Python37\\Scripts;%PATH%"
  - "SET PYTEST_ADDOPTS=-vv"
  - "ECHO PATH=%PATH%"

build: off

install:
  - pip3 install poetry
  - poetry install

test_script:
  - poetry run pytest -s --cov=isort/ --cov=test_isort.py --cov-report=term-missing --cov-report html
